CREATE TABLE twitter_users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id text NOT NULL,
  screen_name text NOT NULL,
  name text NOT NULL,
  description text,
  location text,
  url text,
  is_verified boolean DEFAULT FALSE NOT NULL,
  is_protected boolean DEFAULT FALSE NOT NULL,
  is_coauthored boolean DEFAULT FALSE NOT NULL,
  is_translator boolean DEFAULT FALSE NOT NULL,
  statuses_count int NOT NULL DEFAULT 0,
  following_count int NOT NULL DEFAULT 0,
  followers_count int NOT NULL DEFAULT 0,
  likes_count int NOT NULL DEFAULT 0,
  listed_count int NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  fetched_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  blocked_at timestamp with time zone,
  muted_at timestamp with time zone,
  ui_language text,
  ui_timezone text,
  withheld_in text,
  withheld_scope text
);

ALTER TABLE twitter_users ADD CONSTRAINT twitter_users_source_id_uniq UNIQUE (source_id);

COMMENT ON COLUMN twitter_users.id IS 'Omelette-internal ID';
COMMENT ON COLUMN twitter_users.source_id IS 'The opaque ID from the Twitter';
COMMENT ON COLUMN twitter_users.screen_name IS 'At-handle of this user';
COMMENT ON COLUMN twitter_users.name IS 'Display name of this user';
COMMENT ON COLUMN twitter_users.description IS 'Bio of this user';
COMMENT ON COLUMN twitter_users.location IS 'Location field on this user’s bio';
COMMENT ON COLUMN twitter_users.url IS 'URL field on this user’s bio';
COMMENT ON COLUMN twitter_users.is_verified IS 'If this user is verified';
COMMENT ON COLUMN twitter_users.is_protected IS 'If this user is private';
COMMENT ON COLUMN twitter_users.is_coauthored IS 'If this user has contributor mode';
COMMENT ON COLUMN twitter_users.is_translator IS 'If this user is a Twitter translator';
COMMENT ON COLUMN twitter_users.statuses_count IS 'The number of tweets and replies this user has';
COMMENT ON COLUMN twitter_users.following_count IS 'The number of accounts this user follows';
COMMENT ON COLUMN twitter_users.followers_count IS 'The number of accounts who follow this user';
COMMENT ON COLUMN twitter_users.likes_count IS 'The number of likes this user has';
COMMENT ON COLUMN twitter_users.listed_count IS 'The number of lists this user is on';
COMMENT ON COLUMN twitter_users.created_at IS 'When the user was created on Twitter';
COMMENT ON COLUMN twitter_users.fetched_at IS 'When Omelette retrieved this user';
COMMENT ON COLUMN twitter_users.blocked_at IS 'If pre-existing block, same as fetched_at, otherwise, when the user was blocked';
COMMENT ON COLUMN twitter_users.muted_at IS 'If pre-existing mute, same as fetched_at, otherwise, when the user was muted';
COMMENT ON COLUMN twitter_users.ui_language IS 'Language this user has set their UI to';
COMMENT ON COLUMN twitter_users.ui_timezone IS 'Timezone this user has set their UI to';
COMMENT ON COLUMN twitter_users.withheld_in IS 'Countries this user or their tweets are withheld in';
COMMENT ON COLUMN twitter_users.withheld_scope IS 'Scope of withholding';
